[general.vars]
local_heap_type = "$type$Rc"
local_heap_path = "$type$alloc::rc::Rc"
shared_heap_type = "$type$Arc"
shared_heap_path = "$type$alloc::sync::Arc"
boxed_heap_type = "$type$Box"
boxed_heap_path = "$type$std::boxed::Box"

[fragment_lists]
str_type_impls = ["flex_struct", "flex_impls", "type_aliases"]

# *** str ***

[files.str]
path = "std_str.rs"
fragment_list = "str_type_impls"

[files.str.vars]
suffix = "Str"
str_type = "$type$str"
heap_type = "$type$[u8]"

# *** BStr ***

[files.b_str]
path = "b_str.rs"
fragment_list = "str_type_impls"

[files.b_str.vars]
suffix = "BStr"
str_type = "$type$BStr"
heap_type = "$type$[u8]"
