[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "create"
harness = false

[[bench]]
name = "clone"
harness = false

[[bench]]
name = "convert"
harness = false

[[bench]]
name = "ops"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.3"
flexstr = { path = "../flexstr", features = ["fp_convert", "int_convert"] }
